### ISSUE TITLE
FS17 upgrade?

### ISSUE THREAD

**Issue by DeckerMMIV** [DeckerMMIV/FarmSim_Mod_FollowMe#10]
Your question: Is this going to be upgraded to FS17?

My answer: Yes it is. - Hopefully available via the in-game mod browser.

**Comment by mereman** [comment]
Great news

**Comment by Dzi4d3k** [comment]
Can wait to see it in game 👍

**Comment by BlackFox403** [comment]
Hi DeckerMMIV, a while back I had messaged you about FollowMe and the Reverse Driving Mode (some tractors such as MBTracs allow you to rotate cab and drive backwards). We have an issue when the leader is in "reverse driving" mode, the follower does not follow. You had suggested to me it may be a small code change, but I still cannot get it to work in FS15. Since you will be porting into FS17, will you be able to address this particular mode? I ask because the MBTracs we use in FS15 are being ported into FS17 and with this feature it would be great to have the follower still follow regardless of which mode is used.

Regards

**Comment by DeckerMMIV** [comment]
@BlackFox403 - I did a simple code-alteration in my *almost-upgraded* FollowMe regarding that 'reverse driving', but unfortunately it of cause wasn't "just flipping a switch", as the follower wouldn't do as expected.
So more 'thinking' is needed, to figure out a solution.

**Comment by Sythos** [comment]
If you need a tester give a call :D 

By the way, why not each leader send each 5 meters done (up the directions) to the follower, and the follower move across the "path" each time the leader go far than distance setup (smoothing turns, accelerations and brake, skipping if 2 points are too close and follower cannot match all). In this way each relationship leader-follower is indipendent and the the fact the leader of follower is using a reverse gear shouldn't affect.

**Comment by DeckerMMIV** [comment]
@Sythos - I do not understand your "send each 5 meters done" suggestion.

However the "skipping if 2 points are too close" is something I have been pondering about. Actually it is not the problem of "too close", but more "vehicle is too much perpendicular and in speed going towards a destination point" that is the cause of the zig-zag.

I need to alter the "follow the trail-crumbs" code, so it examines the angle the vehicle is approaching from, and if "too steep" then it should decide if needing to choose the next destination point in the trail (and so forth).

The 'reverse gear' - which I suppose you mean 'reverse driving' - may look like it is "a simple problem as such", but due to how the FS17 base-scripts works, it poses a problem for me. There are too many unknowns and derivatives I have yet to study in the base-scripts, to fully understand what is going on.

LUA is a simple language. If you already know C/C++ then LUA should be no problem for you to understand, once you've read the few semantic/syntax rules. - The "FS17 framework (base-scripts)" however, as with any "framework" (STL, BOOST, etc.) takes time to study and understand.

**Comment by Sythos** [comment]
this issue can be closed, i think :D

**Comment by DeckerMMIV** [comment]
Yes :smile: 
http://www.farming-simulator.com/mod.php?mod_id=55367&title=fs2017
