### ISSUE TITLE
Error when using Follow-me in dedi server

### ISSUE THREAD

**Issue by PromGames** [DeckerMMIV/FarmSim_Mod_FollowMe#11]
Hi @DeckerMMIV ,

This is the error in the log from a tractor when using followme FS17 with a harvester in standard game hired Worker. 

Edit: only happens when you have two or three followers in chain. Not in a one to one set.

`Load mod: FS17_DCK_Compass
Load mod: FS17_DCK_FollowMe
Load mod: FS17_DCK_VehicleGroupsSwitcher`
**--First Part of the error**
Error: Running LUA method 'packetReceived'.
`C:/Users/Alfredo/Documents/My Games/FarmingSimulator2017/mods/FS17_DCK_FollowMe/FollowMe.lua:642: attempt to index field 'currentHelper' (a nil value)
data/vehicles/steerable/jcb/jcbFastrac3000.i3d (53.44) ms
Warning (LUA): 'streamWriteUInt8': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (604): expectedType == Value::VoidType
LUA call stack:
  =dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (0) : streamWriteUInt8
  =dataS/scripts/network/Connection.lua (0) : writeStream
  =dataS/scripts/vehicles/specializations/AIVehicle.lua (0) : sendEvent
  =dataS/scripts/vehicles/specializations/AIVehicle.lua (0) : startAIVehicle
  =dataS/scripts/vehicles/Vehicle.lua (0) : update
  =dataS/scripts/network/Client.lua (0) : update
  =dataS/scripts/BaseMission.lua (0) : update
  =dataS/scripts/FSBaseMission.lua (0) : update
  =dataS/scripts/missions/mission00.lua (0) : update
  =dataS/scripts/main.lua (0) : update
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/AIVehicle.lua:0: attempt to index field 'currentHelper' (a nil value)
Warning (LUA): 'streamWriteUInt8': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (604): expectedType == Value::VoidType
LUA call stack:
  =dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (0) : streamWriteUInt8
  =dataS/scripts/network/Connection.lua (0) : writeStream
  =dataS/scripts/vehicles/specializations/AIVehicle.lua (0) : sendEvent
  =dataS/scripts/vehicles/specializations/AIVehicle.lua (0) : startAIVehicle
  =dataS/scripts/vehicles/Vehicle.lua (0) : update
  =dataS/scripts/network/Client.lua (0) : update
  =dataS/scripts/BaseMission.lua (0) : update
  =dataS/scripts/FSBaseMission.lua (0) : update
  =dataS/scripts/missions/mission00.lua (0) : update
  =dataS/scripts/main.lua (0) : update
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/AIVehicle.lua:0: attempt to index field 'currentHelper' (a nil value)
Warning (LUA): 'streamWriteUInt8': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (604): expectedType == Value::VoidType
LUA call stack:
  =dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (0) : streamWriteUInt8
  =dataS/scripts/network/Connection.lua (0) : writeStream
  =dataS/scripts/vehicles/specializations/AIVehicle.lua (0) : sendEvent
  =dataS/scripts/vehicles/specializations/AIVehicle.lua (0) : startAIVehicle
  =dataS/scripts/vehicles/Vehicle.lua (0) : update
  =dataS/scripts/network/Client.lua (0) : update
  =dataS/scripts/BaseMission.lua (0) : update
  =dataS/scripts/FSBaseMission.lua (0) : update
  =dataS/scripts/missions/mission00.lua (0) : update
  =dataS/scripts/main.lua (0) : update
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/AIVehicle.lua:0: attempt to index field 'currentHelper' (a nil value)
Warning (LUA): 'streamWriteUInt8': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (604): expectedType == Value::VoidType
LUA call stack:
  =dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (0) : streamWriteUInt8
  =dataS/scripts/network/Connection.lua (0) : writeStream
  =dataS/scripts/vehicles/specializations/AIVehicle.lua (0) : sendEvent
  =dataS/scripts/vehicles/specializations/AIVehicle.lua (0) : startAIVehicle
  =dataS/scripts/vehicles/Vehicle.lua (0) : update
  =dataS/scripts/network/Client.lua (0) : update
  =dataS/scripts/BaseMission.lua (0) : update
  =dataS/scripts/FSBaseMission.lua (0) : update
  =dataS/scripts/missions/mission00.lua (0) : update
  =dataS/scripts/main.lua (0) : update
Error: Running LUA method 'update'.`

**After reseting the vehicle**
`dataS/scripts/vehicles/specializations/AIVehicle.lua:0: attempt to index field 'currentHelper' (a nil value)
Error: Running LUA method 'packetReceived'.
dataS/scripts/FSBaseMission.lua:0: attempt to index field 'currentHelper' (a nil value)
Error: Running LUA method 'packetReceived'.
dataS/scripts/FSBaseMission.lua:0: attempt to index field 'currentHelper' (a nil value)
Warning (Script): Unknown entity id 103694 in method 'getWorldTranslation'.
LUA call stack:
  =C:/Users/Alfredo/Documents/My Games/FarmingSimulator2017/mods/FS17_DCK_FollowMe/FollowMe.lua (1211) : getWorldTranslation
  =C:/Users/Alfredo/Documents/My Games/FarmingSimulator2017/mods/FS17_DCK_FollowMe/FollowMe.lua (1273) : getWorldToScreen
  =dataS/scripts/vehicles/Vehicle.lua (0) : draw
  =dataS/scripts/BaseMission.lua (0) : draw
  =dataS/scripts/FSBaseMission.lua (0) : draw
  =dataS/scripts/missions/mission00.lua (0) : draw
  =dataS/scripts/main.lua (0) : draw
Warning (Script): Unknown entity id 103694 in method 'getWorldTranslation'.
Warning (LUA): 'streamWriteUInt8': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (604): expectedType == Value::VoidType
LUA call stack:
  =dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (0) : streamWriteUInt8
  =dataS/scripts/network/Connection.lua (0) : writeStream
  =dataS/scripts/vehicles/specializations/AIVehicle.lua (0) : sendEvent
  =dataS/scripts/vehicles/specializations/AIVehicle.lua (0) : startAIVehicle
  =dataS/scripts/vehicles/Vehicle.lua (0) : update
  =dataS/scripts/network/Client.lua (0) : update
  =dataS/scripts/BaseMission.lua (0) : update
  =dataS/scripts/FSBaseMission.lua (0) : update
  =dataS/scripts/missions/mission00.lua (0) : update
  =dataS/scripts/main.lua (0) : update
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/AIVehicle.lua:0: attempt to index field 'currentHelper' (a nil value)
Warning (LUA): 'streamWriteUInt8': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (604): expectedType == Value::VoidType
Error: Running LUA method 'packetReceived'.
dataS/scripts/FSBaseMission.lua:0: attempt to index field 'currentHelper' (a nil value)
Error: Running LUA method 'packetReceived'.
dataS/scripts/FSBaseMission.lua:0: attempt to index field 'currentHelper' (a nil value)
Error: Running LUA method 'packetReceived'.
dataS/scripts/FSBaseMission.lua:0: attempt to index field 'currentHelper' (a nil value)
Error: Running LUA method 'packetReceived'.
dataS/scripts/FSBaseMission.lua:0: attempt to index field 'currentHelper' (a nil value)
Error: Running LUA method 'packetReceived'.
dataS/scripts/FSBaseMission.lua:0: attempt to index field 'currentHelper' (a nil value)
Error: Running LUA method 'packetReceived'.
dataS/scripts/FSBaseMission.lua:0: attempt to index field 'currentHelper' (a nil value)
Error: Running LUA method 'packetReceived'.
dataS/scripts/FSBaseMission.lua:0: attempt to index field 'currentHelper' (a nil value)
Error: Running LUA method 'packetReceived'.
dataS/scripts/FSBaseMission.lua:0: attempt to index field 'currentHelper' (a nil value)`

After the error happens, the follower is saying, I am not able to find the leader, but follow me continues having the control of the vehicle, and you can not disengage from the leader with the Right ctrl F.

The vehicle is not able to move, however, commands still works, like Ctrl H (waiting), In dedicated servers, you need to re start the server to stop this blockage.

 A curious thing that also happens is that you can reset the vehicle and the follow me is stoped, but a draw of the player remains in the place from where the vehicle has been reset, And a continues error appears in the log.

**Comment by DeckerMMIV** [comment]
I will look into it.

**Comment by PromGames** [comment]
I was testing more the issue and I detect that the system works fine if you disconnect the followers in the contrary order as you connect. This means that all vehicles are disconnected when they have only the role of follower. and you do not produce orphan followers that is the error produced.

The solution could be a routine that check before disconnect if the vehicle has one or two roles, If have one works OK and proceed to disconnect,

In case the vehicle has the two roles, we have two options:
1. Message warning and block the possibility of disconnection. 
2. Make the orphan follower to follow the new leader.

Could be third one, spliting the chain 
3. Automatically make the orphan follower to stop the condition of follower but maintain the condition of leader of the next one.

My preference would be the third

**Comment by DeckerMMIV** [comment]
Please download the version 1.1.0.35, and see if it fixes the problem.

**Comment by DeckerMMIV** [comment]
Closing this issue, due to it being very old.
