### ISSUE TITLE
Cancelling Follow, but tractor still following

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_FollowMe#15]
A few times I have cancelled follow me at the end of a row, and the tractor is still following the combine..  though when I press the Cntrl F to follow again, it says there is no path to follow, get closer..

the only way to regain control of the tractor is to quit and restart

**Comment by sootysax** [comment]
here is the log when this error occurs:

https://gist.github.com/sootysax/2b32d5f14e9291741d74f82f1a880a62

**Comment by DeckerMMIV** [comment]
I know of that bug, which hopefully will be fixed in the next version.

**Comment by Dzi4d3k** [comment]
Not sure if this is the same issue, but playing on dedicated server if we leave game without disabling followers then after back to game there is similar issue to @sootysax.
It is not possible to disable follow mode with mentioned message. However we found workaround.
We have drive away with previous leader and bring new one in front of blocked vehicle and try to enable/disable follow mode, and then following vehicle became unlocked.

**Comment by DeckerMMIV** [comment]
Please download the version 1.1.0.35, and see if it fixes the problem.

**Comment by Dzi4d3k** [comment]
My test with version 1.1.0.35 show that there is no longer such issues.
