### ISSUE TITLE
Backing up and correcting path

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_FollowMe#21]
In FS15, if you had a tractor following you, and you missed a turn, you could back up and make the turn, and the tractor following would take the corrected path and make the turn...

now the tractor will follow the original path and overshoot the turn...

**Comment by DeckerMMIV** [comment]
That could depend on the "trail" that the leading vehicle have put down, and how far the "wrong trail" was.

There have actually not been made any 'trail following algorithm' changes from the FS15 version to the v1.0.0.17 for FS17, so I think the same could/would happen in FS15.

**Comment by DeckerMMIV** [comment]
Please download the version 1.1.0.35, and see if it fixes the problem.

**Comment by DeckerMMIV** [comment]
Closing this issue, due to it being very old.
