### ISSUE TITLE
Vehicle blocked when unfollowed by player

### ISSUE THREAD

**Issue by Dzi4d3k** [DeckerMMIV/FarmSim_Mod_FollowMe#23]
Not sure if this is issue, but being in following vehicle it follow mode is disable, than vehicle is blocked, and there is need to turn of engine and turn on it again to be able to drive freely.

Additionally disabling following vehicle from leader cause follower to turn of engine. As far as I remember in FS15 engine stood enabled in similar case.

**Comment by DeckerMMIV** [comment]
Please download the version 1.1.0.35, and see if it fixes the problem.

**Comment by Dzi4d3k** [comment]
I can confirma that issue is now solved with version 1.1.035.
