### ISSUE TITLE
No show help in panel Help // No work MP

### ISSUE THREAD

**Issue by Vanquish081** [DeckerMMIV/FarmSim_Mod_FollowMe#25]
I can't see the help for Follow Me in panel Help (F1), this help no show here.

**Comment by Dzi4d3k** [comment]
Maybe you encountered the new8-items limit in Help box which is now happing in FS17 as a new functionality. 
Basically the options are still there by not displayed, because are considered by game as less important because rarely used.

**Comment by Vanquish081** [comment]
Not shown any and I tried with this mod only in folder mod.

**Comment by Dzi4d3k** [comment]
- Game log errors?
- Game patch 1.3.1 present?
- Mod selected on game start?
- Follow Me version 1.1.0.35 used?

Very confusing as mine works perfectly fine.

**Comment by Vanquish081** [comment]
The mod no work... rctrl + F only on/off the light vehicle.

![Example](http://i.imgur.com/aAPvPl3.jpg)
![Example](http://i.imgur.com/5HYRXce.jpg)

Log - http://pastebin.com/Ty8Jw86c

**Comment by Dzi4d3k** [comment]
Not sure if this could has any influence, but did you tried it without joystick connected? From screenshoot seems that menu is adjusted to work with joystick. Maybe setting in game bottom bindings could help. As far as I remember there are no default bindings for game controllers in Follow Me.

**Comment by Vanquish081** [comment]
I understand you, but the other command with keyboard work fine.

**Comment by DeckerMMIV** [comment]
I have noticed that particular "problem" in YouTube lets-plays I've been watching, showing the v1.0.0.17.

It could have some relation to the joystick/gamepad that Dzi4d3k mentions. - Probably some new "hidden code" that GIANTS have introduced, when the game thinks that it should only show joystick/gamepad icons in the help-box.

**Comment by DeckerMMIV** [comment]
Closing this issue, due to it being very old.
