### ISSUE TITLE
Does breadcrumb trail include speed info?

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_FollowMe#28]
Wondering if the following vehicles are taking into account the turn speed of the leading vehicle?

I'm playing with the new More Realistic beta and am finding that my following vehicles are prone to tipping over at corners and turns, no matter how slowly the leading vehicle takes the turns, the following vehicles barrel through the turns and tip over.

**Comment by sootysax** [comment]
https://fs-uk.com/forum/index.php?topic=195659.msg1273853#msg1273853

**Comment by DeckerMMIV** [comment]
I have noticed that too. - For now (work-around), I just don't let followers get too much behind, as they will then 'speed to catch up'.

Will at some time look into trying to get FollowMe understand MR vehicles a bit better. - The past FS2013 FollowMe code changes for MR wasn't exactly good either.

Maybe some more "intelligent" code (i.e. more math), so it gets some ability to "look into the future breadcrumb-trail" and detect when approaching a turn which is dangerous for the "current present speed".

**Comment by sootysax** [comment]
welcome back!

**Comment by DeckerMMIV** [comment]
Attempted "simple fix" in v1.2.2.43, whereby MR vehicles are disallowed to 'speed up to catch up'. Also they apply brakes if going faster than allowed at the breadcrumbs.
