### ISSUE TITLE
Port on FS19 in plans?

### ISSUE THREAD

**Issue by Sythos** [DeckerMMIV/FarmSim_Mod_FollowMe#30]
Any plan to port FollowMe on FS19? :D

**Comment by genen** [comment]
Ditto! Amazingly they didn't implement it in game natively, so on to mod authors again to make this ESSENTIAL function!

**Comment by Sythos** [comment]
> Ditto! Amazingly they didn't implement it in game natively, so on to mod authors again to make this ESSENTIAL function!

Modder are and will be always essential, Giant give a platform and something to play on, but 90% are from people like Decker :)

**Comment by DeckerMMIV** [comment]
Yes, there is an upgrade of FollowMe coming to FS19. - I have been working on it for the last 4-5 weeks, and am somewhat "ready" for sending it to GIANTS' ModHub.

Though I think 'the community' should have a change of fixing/correcting my badly used machine translations for the other languages. - So just now I have committed a `FS2019_TranslationFiles` branch, which contains only the XML files.

**Comment by sootysax** [comment]
amazing news!  thank you!

**Comment by DeckerMMIV** [comment]
Submitted to ModHub, so now we wait. :hourglass_flowing_sand:

**Comment by AgroMeester** [comment]
Great news! Thank you!

**Comment by Anonymous-any** [comment]
Hello,
"committed a FS2019_TranslationFiles branch, which contains only the XML files."
many many thank for your upgrade job's and I will try to remember.
Salutations

**Comment by sootysax** [comment]
> Submitted to ModHub, so now we wait. ⏳

and wait... and wait :)

**Comment by sootysax** [comment]
So, did Follow Me get rejected?  Its off the testing list and not on modhub :(

**Comment by DeckerMMIV** [comment]
Yeah :disappointed: - Their response:
> We could not certify your mod Follow Me. Please review your mod and resubmit again.
> 
> Certification Report:
> Since your mod uses the same name in every language, please only use an EN title inside the title tag of your modDesc.
> Maybe it is possible for you to check whether the following vehicle has traffic in front of it. There were little problems while crossing streets or making turns at a intersection. Otherwise all seems fine.


The first one is very easy to fix, and I should hopefully have time to do that later today, so it can be quickly resubmitted. - Their second suggestion will take more time.

**Comment by sootysax** [comment]
cool should only be another 4 weeks to get back through the queue..  i sure do miss the pre-modhub fs2013 days

**Comment by Roby1164** [comment]
Here someone releases a fake version for FS19 .....
http://www.farmingsimulator19mods.com/follow-me-v1-2-1-40-fs19/

**Comment by Roby1164** [comment]
Among other things he also made a video on Youtube:
https://www.youtube.com/watch?time_continue=6&v=Y8QhRLLFJsg

**Comment by Mattia-1998** [comment]
It's fake, that mod no work....

**Comment by Roby1164** [comment]
> Yeah 😞 - Their response:
> 
> > We could not certify your mod Follow Me. Please review your mod and resubmit again.
> > Certification Report:
> > Since your mod uses the same name in every language, please only use an EN title inside the title tag of your modDesc.
> > Maybe it is possible for you to check whether the following vehicle has traffic in front of it. There were little problems while crossing streets or making turns at a intersection. Otherwise all seems fine.
> 
> The first one is very easy to fix, and I should hopefully have time to do that later today, so it can be quickly resubmitted. - Their second suggestion will take more time.

Doesn't it have the chance to have it, to give it to you?

**Comment by DeckerMMIV** [comment]
> Doesn't it have the chance to have it, to give it to you?

I have no idea what it is you are trying to say there.

Anyway - as some may have noticed - 'Follow Me' is once again on GIANTS' mods testing list... So hopefully this time... :crossed_fingers:

**Comment by Roby1164** [comment]
> > Doesn't it have the chance to have it, to give it to you?
> 
> I have no idea what it is you are trying to say there.
> 
> Anyway - as some may have noticed - 'Follow Me' is once again on GIANTS' mods testing list... So hopefully this time... 🤞

Sorry, crazy translator .....
I meant to say if there was the possibility of having it to try it, but if it comes for everyone, in the mods, ok let's wait ..

**Comment by DeckerMMIV** [comment]
Mod has now been officially published on GIANTS' ModHub, so closing this issue.
