### ISSUE TITLE
Combine stopping

### ISSUE THREAD

**Issue by Nielsen362** [DeckerMMIV/FarmSim_Mod_FollowMe#33]
Hi
I have a problem when i use follow me with combines, the follower always stops at the headland instead of following me in to a new track, then i restart and it follows to the other end and it repeats, hope there is a fix
thanks in advance
Nielsen

**Comment by DeckerMMIV** [comment]
Is this still an issue with version 1.1.0.2 of 'Follow Me'?

If so, what is your setup of vehicles? I.e. their types, and what they do. Screenshot(s) will help to explain.
Remember that 'Follow Me' will not follow vehicles that goes in reverse. - Could also be that the combine is doing a really sharp U-turn, which the follower vehicle can't correctly cope with.

**Comment by Nielsen362** [comment]
Yes it is just tested it again, here is some pictures. I have used follow me in fs 15 and 17 so i have some experience with this great mod :-). I always have the follower on the outside of me when i am turning
Thanks in advance 
Nielsen

![20190415164458_1](https://user-images.githubusercontent.com/25202637/56142705-69254600-5f9f-11e9-82e8-4d57d67ae88a.jpg)
![20190415164542_1](https://user-images.githubusercontent.com/25202637/56142706-69254600-5f9f-11e9-9da6-0b13b2809101.jpg)
![20190415164724_1](https://user-images.githubusercontent.com/25202637/56142707-69254600-5f9f-11e9-8ddf-9c79aa2efaab.jpg)
![20190415165017_1](https://user-images.githubusercontent.com/25202637/56142708-69bddc80-5f9f-11e9-8b46-a0635b0fd3fd.jpg)
![20190415165024_1](https://user-images.githubusercontent.com/25202637/56142710-69bddc80-5f9f-11e9-9582-aad727633650.jpg)

**Comment by DeckerMMIV** [comment]
Thank you for the images. They showed something completely different, than what I thought from your initial explanation.

I tracked the issue down to being the 'cutter' that is the cause. Apparently it has some AI-code in its script, which causes the AI-vehicle to stop, if there hasn't been anything to harvest for 5 seconds. - Line 765 in this method; https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=70&class=10484#getAllowCutterAIFruitRequirements165737

Will now try to figure out, how to get my Follow Me script to "ignore" such a situation for combine+cutter.

**Comment by Nielsen362** [comment]
Thank you for your great work, looking forward to the fix 😊

**Comment by DeckerMMIV** [comment]
Try with version 1.3.0.6 of 'Follow Me', that has just been made available on ModHub, to see this problem is solved.

**Comment by Nielsen362** [comment]
I will as soon as possible 😄 thanks

**Comment by Nielsen362** [comment]
Working just perfect 👍
