### ISSUE TITLE
White HUD text always on

### ISSUE THREAD

**Issue by 51stHD** [DeckerMMIV/FarmSim_Mod_FollowMe#34]
The white HUD text was only visible in FS17 version (& FS15 I think) when you held down the CTRL button. Now it's on all the time from when you engage Follow Me.

Any chance of having it as it was in FS17?, or at least an option disable it for those of us who prefer a less info cluttered screen.

Thanks again for this essential mod anyhow :)

**Comment by DeckerMMIV** [comment]
Unfortunately in FS19 the input-system have changed quite a bit, so I have not found a "good method" to detect if the modifier-key (<kbd>CTRL</kbd>/<kbd>SHIFT</kbd>/<kbd>ALT</kbd>) is pressed or not, depending of if it is actually binded to the input-action.

What I might do instead, is to have the text 'fade away', after a few seconds of the last "instruction" given. - But this effect however, will then only "make text visible again" when a new 'Follow Me'-"instruction" is issued to the vehicle.

**Comment by 51stHD** [comment]
That would be great for as it is, it's a little invasive and you only really need it when you're giving "instructions".

Thanks again

**Comment by DeckerMMIV** [comment]
Version 1.3.0.6 of 'Follow Me' has just been updated on ModHub.
It includes a 'fade away' feature, so the text isn't visible for too long.
