### ISSUE TITLE
Looking for FS17 final version 1.2.2.44 download?

### ISSUE THREAD

**Issue by Dwinesk** [DeckerMMIV/FarmSim_Mod_FollowMe#35]
Hi. I am still playing on fs17 and have been searching on here for your final fs17 edit of this mod (I am having that issue with more realistic mod). I had not been on here for a while so was unaware of the fix you had provided. Can you please aid me with a link to version 1.2.2.44. Thanks

**Comment by DeckerMMIV** [comment]
You can browse the [commit history](https://github.com/DeckerMMIV/FarmSim_Mod_FollowMe/commits/master), select an older one, and then browse the repository at that time:
![image](https://user-images.githubusercontent.com/2834184/57630468-f4ddc280-759d-11e9-9438-da5a8d0f3edf.png)

Then GitHub has a feature, where you can download the repository contents at that time, as a ZIP-file:
![image](https://user-images.githubusercontent.com/2834184/57630610-34a4aa00-759e-11e9-8747-43ff9182457d.png)

You then have to create a FS17-mod of the downloaded ZIP-file-files. - Basically extract the 'FollowMe' folder from the ZIP-file, and place in your FS17 `mods` folder (remember to remove the older FollowMe.ZIP)

**Comment by Dwinesk** [comment]
Thank you for the instructions. I managed to get it, now to play it to my hearts content :)
