### ISSUE TITLE
Wages

### ISSUE THREAD

**Issue by stangman04** [DeckerMMIV/FarmSim_Mod_FollowMe#36]
I assume Followme works off the ingame Hired worker somehow and charges wages when in use, is there a way to turn off wages for using followme? Just curious.

**Comment by DeckerMMIV** [comment]
The wages for FollowMe are set to to be only 20% of the normal AI wages.
https://github.com/DeckerMMIV/FarmSim_Mod_FollowMe/blob/master/FollowMe/FollowMe.lua#L221

And no, there is no easy way to turn off wages.
