### ISSUE TITLE
Problem with slurry tankers

### ISSUE THREAD

**Issue by Luxor86** [DeckerMMIV/FarmSim_Mod_FollowMe#40]
Hi Decker, i'm using the Follow Me version 1.6.0.29. 
The follower turn on the tanker when the follower is connected with the slurry tanker and to his relative injector. If the injector is not connected the follower don't turn on the slurry tanker. I've tested on Felsbrun and Ravenport with not other mod installed and the mod directory with just Follow Me mod inside.

**Comment by DeckerMMIV** [comment]
I have reproduced it, and probably found a "hack'ish work-around" for it _(after 3 hours digging in scripts)._

Now I need to do some thorough testing, to ensure that my "hack" have not caused any other noticeable bugs/side-effects.

**Comment by Luxor86** [comment]
Wow nice. Thanks for your work Decker
