### ISSUE TITLE
New Tractor Mod Question

### ISSUE THREAD

**Issue by jrd387** [DeckerMMIV/FarmSim_Mod_FollowMe#41]
I am developing a new tractor for FS19 and would like to know what "Follow Me" looks for or needs in the mod XML for Follow Me to work correctly with the tractor. 

Thanks,

Jrd387

**Comment by DeckerMMIV** [comment]
That the vehicle's vehicle-type contains specializations; Lights, Motorized, Enterable, Drivable & AIVehicle. - And not; ConveyorBelt nor Locomotive.

So you must make sure, you design & code your vehicle along the same specifications as the game's default vehicles.

**Comment by jrd387** [comment]
Thanks Decker!
