### ISSUE TITLE
[Translation Added] Translation File for Simplified Chinese

### ISSUE THREAD

**Issue by mat-wang** [DeckerMMIV/FarmSim_Mod_FollowMe#46]
Hi,

This is a great mod for fs19, but there isn't a translation for Simplified Chinese. Hence, I create one by myself. Could you please add it into next version?

Thanks!

Sorry for couldn't upload a xml file.

[modDesc_l10n_cs.txt](https://github.com/DeckerMMIV/FarmSim_Mod_FollowMe/files/4564721/modDesc_l10n_cs.txt)

**Comment by DeckerMMIV** [comment]
Obsolete - FS22 version released.
