### ISSUE TITLE
Brazilian portuguese translation (Tradução PT-BR)

### ISSUE THREAD

**Issue by nagyslash** [DeckerMMIV/FarmSim_Mod_FollowMe#48]
New here. don't even know if its the right place, but i'd made the Brazilian portuguese translation.

[modDesc_l10n_br.txt](https://github.com/DeckerMMIV/FarmSim_Mod_FollowMe/files/4949464/modDesc_l10n_br.txt)

**Comment by elizandro-policena** [comment]
Olaa... tbmm sou novo, esse arquivo é só copiar e substituir na pasta?

**Comment by nagyslash** [comment]
Baixe o arquivo e cole na pasta do FollowMe.
Não vai pedir pra substituir nada, pq não tinha arquivo de tradução BR.

**Comment by elizandro-policena** [comment]
Precisa alterar algo no ModDesc? Pra abrir com a tradução BR..

Em dom, 9 de ago de 2020 21:50, Nagyx <notifications@github.com> escreveu:

**Comment by nagyslash** [comment]
NESSE caso não, pq as traduções desse mod ficam em ModDesc"s diferentes. Ou seja, é um ModDesc pra cada idioma.

**Comment by DeckerMMIV** [comment]
Obsolete - FS22 version released.
