### ISSUE TITLE
Possible English-language localization support or assistance?

### ISSUE THREAD

**Issue by MisterFister2016** [DeckerMMIV/FarmSim_Mod_FollowMe#50]
Hello there.  I'm not a programmer, but I might be able to help with improving English-language items for your mod, whether they be embedded remarks hidden within the code for future programmers who may want to derive work (assuming you allow for that sort of thing) or with player-visible English-language text and descriptions within the game or within the game client.

In particular, I can help address idioms, figures of speech, and other common expressions that might not trans-literate well for a first-langeage English speaker.  This includes issues such as spelling, grammar, word choice, syntax (word-sequence) references, references to technical or non-conversational terminology such as jargon or slang, and general immersion and intelligibility.

The only language in which I am entirely-fluent is English, but I do have a sizeable network of multilingual friends.  Through several notable first-language-non-English-speaking friends / associates / past associates, I have some meaningful level of access to languages such as German, Spanish, Polish, Latin, Chinese, to name just a few.  I can also speak with some knowledge on various cultural / geographical / dialect differences -- for example, sometimes it is helpful to distinguish between USA English, UK English, England-English (England is only one part of the United Kingdom, and even within the United Kingdom there can be some terminology or spelling differences).  For example, even USA English varies between USA regions.  Similarly, there are sometimes key differences in work meanings and common word choices between USA English, Canadian English, Australian English, and other major English dialects and "regionalects".

I anticipate that some source materials might benefit from me being able to correspond with the source's original creator so that I can learn for myself what contexts or subtleties might be relevant for a particular length of material.  This might include source material that I receive in original non-English, or even in English or translated-English that could benefit from edits and improvements.

I anticipate that sometimes, I might benefit from being able to learn some of the original person's intent to better guide me -- but I anticipate that this will likely be the exception for me, and not a standing practice.

Thanks for making a wonderful mod, and I hope I get the opportunity to contribute!

**Comment by DeckerMMIV** [comment]
Obsolete - FS22 version released.
