### ISSUE TITLE
Idea: The leading vehicle wait for the following vehicle if the distance exceeds x% of the set distance.

### ISSUE THREAD

**Issue by wallsingham** [DeckerMMIV/FarmSim_Mod_FollowMe#51]
hello @DeckerMMIV 
Thank you for this mod. I really like FollowMe.

What do you think of the possibility that the leading vehicle will wait for the following vehicle if the distance exceeds x% of the set distance?
I use FollowMe for baling behind the combine. Sometimes the tractor stops with the baler for some reason. (no fuel, obstacles, etc.). But the harvester keeps working ... Then you have to manually stop the combine and manually drive the tractor to do the job until you reach the combine.
So I would find it useful if the leading vehicle could wait for the following vehicle when x% of the set distance is exceeded.
 
##German##
Vielen Dank für FollowMe. Ich benutze es sehr gern und oft. :-)

Was hälst du von der Möglichkeit, dass das führende Fahrzeug auf das folgende Fahrzeug wartet, wenn der Abstand x% der eingestellten Entfernung überschreitet?
Ich benutze FollowMe zum Ballenpressen hinter dem Mähdrescher. Manchmal stopt der Traktor mit der Ballenpresse aus irgendeinem Grund. (kein Kraftstoff, Weghindernisse usw.). Aber der Harvester arbeitet weiter ... Dann muss man den Mähdrescher manuell anhalten und den Traktor manuell fahren, um die Arbeit zu erledigen, bis der Mähdrescher erreicht ist.
Daher fände ich es nützlich wenn das Führende Fahrzeug auf das folgende Fahrzeug warten könnte, wenn  x% der eingestellten Entfernung überschrieten werden.

Viele Grüße
Hektor

**Comment by DeckerMMIV** [comment]
Wont fix.
Work-around: Decrease the leading vehicle's cruise speed, so it becomes "slow enough" for the followers to not fall behind.
