### ISSUE TITLE
Version for FS22

### ISSUE THREAD

**Issue by guenth39** [DeckerMMIV/FarmSim_Mod_FollowMe#52]
Any plans to bring this to FS22?

**Comment by xno** [comment]
Hi,

new mod for fs22?

**Comment by DeckerMMIV** [comment]
@guenth39 @xno

Yes, I will be looking into upgrading, and perhaps enhancing, my 'Follow Me' mod to FS22.

But "Rome wasn't build in a day", so it will take time - I do also have a 'Real Life(tm)' to attend to ;-)

/Decker_MMIV

**Comment by Clouseau219** [comment]
RL what is this ;) ? Take your time

**Comment by soullesswolf1316** [comment]
are there any news for the follow me fs 22 rework?

**Comment by JuMaH0** [comment]
Is there anything new here?

**Comment by RobertLynnMCK** [comment]
> Is there anything new here?

Do you **_see_** anything new?

**Comment by BattleHook** [comment]
Any update on the upgrade of the 'Follow Me' mod to FS22? 
It is a perfect mod and I miss it dearly when playing FS22.

**Comment by just-some-tall-bloke** [comment]
> Any update on the upgrade of the 'Follow Me' mod to FS22? It is a - almost - perfect mod and I miss it dearly when playing FS22.

Do you _see_ any update in the repository?

**Comment by StrangerrYT** [comment]
Можно-ли узнать, состоится ли релиз Follow Me для FS 22 В ближайшее время? Этот мод это самый нужный мод в FS 200

**Comment by sootysax** [comment]
> May I know if Follow Me will be released for FS 22 anytime soon? This mod is the most needed mod in FS 22

it's really not cool to continue to ask when mods are going to be released...  stop

**Comment by just-some-tall-bloke** [comment]
> its also not cool to not update ppl on the mod when someone says he will maybe release a update.

They can do (or not do) whatever they want. They owe you nothing.

**Comment by DeckerMMIV** [comment]
Released on Giants Software's ModHub:
https://www.farming-simulator.com/mods.php?title=fs2022&org_id=53574
