### ISSUE TITLE
??? is it original, official ??

### ISSUE THREAD

**Issue by Roby1164** [DeckerMMIV/FarmSim_Mod_FollowMe#53]
Here is this version
https://farmingsimulator22mods.com/follow-me-v1-0-fs22/
But here on GitHub there is no trace ...

**Comment by Lactic68** [comment]
Hi,
As far as I know, the mod was released on the modhub : 
[https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=244513&title=fs2022](https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=244513&title=fs2022)

**Comment by DeckerMMIV** [comment]
> But here on GitHub there is no trace ...

Because 'Real Life' intervene. - The source for FS22 version of Follow Me is now here.

And please use Giants Software's ModHub or the in-game 'downloadable content', for downloading it from the official location.
