### ISSUE TITLE
Fire/Halt Follower

### ISSUE THREAD

**Issue by CheTranqui** [DeckerMMIV/FarmSim_Mod_FollowMe#56]
I had one where I was baling and had the follower in an arcusin picking up bales behind me. When I reversed to drop the bale, if I had the follow distance too close, it would confuse the driver and he would sometimes turn into me and ram me from the side...

... with a longer follow distance I found that this was a turn-around maneuver where he would circle behind me to line himself up more accurately.

I want to be able to halt and/or fire the follower while in the lead vehicle.

**Comment by DeckerMMIV** [comment]
'Pause/Resume' ability have been added to version 1.3.0.0, which is now pending GIANTS Software's ModHub verification.
