### ISSUE TITLE
Harvester Issues

### ISSUE THREAD

**Issue by gjames19711** [DeckerMMIV/FarmSim_Mod_FollowMe#59]
In FS22 FollowMe when using two harvesters for harvesting the following harvester stops following at the turnaround when headlands are cut leaving a message of "AI worker has stopped work unexpectedly - unknown reason
![fsScreen_2022_08_25_15_47_14](https://user-images.githubusercontent.com/89527610/186755491-30945986-8c02-4544-929d-029145e68c48.png)

**Comment by DeckerMMIV** [comment]
A fix for 'harvester stopping when no crops to cut' is in version 1.3.0.0, which is currently pending GIANTS Software's ModHub verification.
