### ISSUE TITLE
Turn off baler slowdown @ 90%

### ISSUE THREAD

**Issue by cpjet64** [DeckerMMIV/FarmSim_Mod_FollowMe#60]
Is it possible to get a disable/enable setting for the baler slowdown? Using courseplay with my mower then using follow me for every vehicle behind it (windrower,baler,wrapper,hauler) breaks the followme for the baler because it slows down on its own. my temporary workaround has been managing the speed of all vehicles with cruise control so the first vehicle is moving at 90% of the balers max speed so that way it never leaves it behind.

**Comment by DeckerMMIV** [comment]
A rework of the algorithm for round-balers to 'when nearly full and nothing is picked up then keep working-speed up' have been done to version 1.3.0.0, which is currently pending GIANTS Software's ModHub verification.

Please be aware of that round-balers still needs to slow down right before being 100% full, for avoiding leaving small patches of swaths. - And you are correct in using the "workaround", of having the leading vehicle's cruise control set to a lower speed, for allowing followers to "keep up", in particular those that need to continuously stop/resume.
