### ISSUE TITLE
change: reduce increment from 5m to 2m

### ISSUE THREAD

**Issue by Hyratel** [DeckerMMIV/FarmSim_Mod_FollowMe#62]
some auger wagons are < 5m long, and don't line up with the increments to bring the follower under the harvester unloader spout

**Comment by genen** [comment]
Was there not a version maybe 3-4 years ago that when you HELD the key like ctr-w it would change to single M increments and if you tapped  ctr-w it was 5m increments? I definitely remember something like that... was good to fine-tune... I would also subbed that it be in 2M increments from -5 to +20m.... not starting at 0
